server {
    listen 8081;
    server_name _;
    root /var/www/selectbf;
    index index.php;

    server_tokens off;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\. {
        deny all;
        return 404;
    }

    access_log /var/log/nginx/selectbf_access.log;
    error_log  /var/log/nginx/selectbf_error.log;
}
